### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by Baggerone**

### CODE REVIEW

**Comment by Baggerone** [comment]
I don't know what the purpose of this PR is.  It looks like it's replacing other languages with English text.

**Comment by hobbitronics** [comment]
> I don't know what the purpose of this PR is. It looks like it's replacing other languages with English text.

Correct. I'm not sure why it's doing that. Maybe some translations that were added from a conventional PR aren't in Crowdin. I have to merge a PR before this PR was automatically updated in order to avoid English.

**Review by forevermatt — CHANGES_REQUESTED** [review]
Agreed: this looks like it's _un_-translating things... a step backwards.

**Comment by forevermatt** [comment]
Any objection to me simply closing (rejecting) this PR?

**Pull request closed without merging**
