### PR TITLE
Update vue to 2.7

### PR DESCRIPTION
**Pull request by hobbitronics**
## Changed
- updated to vue 2.7
- changed to composable api in profile/index.vue

## Removed
- vue-template-compiler as part of migration

## Added
- added vue-demi as part of migration

Migration guide
https://v2.vuejs.org/v2/guide/migration-vue-2-7.html

### CODE REVIEW

**Review by forevermatt — COMMENTED** [review]
Unfortunately, I don't know Vue well enough to feel like I can give a meaningful review of this code. 🤷‍♂️

**Comment by Baggerone** [comment]
> Unfortunately, I don't know Vue well enough to feel like I can give a meaningful review of this code. man_shrugging

Is there anyone on our team who does know it well enough to approve it?

**Comment by forevermatt** [comment]
> Is there anyone on our team who does know it well enough to approve it?

Perhaps @briskt?

**Comment by briskt** [comment]
> > Is there anyone on our team who does know it well enough to approve it?
> 
> Perhaps @briskt?

Not really. In my IDP work, I didn't do anything with Vue. I did scratch the surface of learning it, but am far from proficient.

**Comment by briskt** [comment]
@hobbitronics is there a compelling reason to update the Vue version? Not that I'm opposed to keeping up to date. Just curious if there's an end-of-life or security issue.

**Comment by hobbitronics** [comment]
> @hobbitronics is there a compelling reason to update the Vue version? Not that I'm opposed to keeping up to date. Just curious if there's an end-of-life or security issue.

Vue 2 is eol, but 2.7 gets extended lts and they have backported a lot of Vue 3 features. See https://v2.vuejs.org/lts/
The refactoring I did is not necessary, but I thought using the [Composition API](https://vuejs.org/guide/extras/composition-api-faq.html#composition-api-faq) is a lot easier, especially for someone who knows Svelte. We can keep it how it was though.

**Comment by briskt** [comment]
> > @hobbitronics is there a compelling reason to update the Vue version? Not that I'm opposed to keeping up to date. Just curious if there's an end-of-life or security issue.
> 
> Vue 2 is eol, but 2.7 gets extended lts and they have backported a lot of Vue 3 features. See https://v2.vuejs.org/lts/ The refactoring I did is not necessary, but I thought using the [Composition API](https://vuejs.org/guide/extras/composition-api-faq.html#composition-api-faq) is a lot easier, especially for someone who knows Svelte. We can keep it how it was though.

OK, thanks. Sounds like a good reason to move forward. I'll go ahead and approve, trusting that you've done your homework and sufficient testing. (Or will do so on the staging IDP)

**Review by briskt — APPROVED** [review]
Approved for further testing

**Pull request merged**
